### ISSUE TITLE
Comparison of char and memo fields may result in values not being added to spreadsheet.

### ISSUE THREAD

**Issue by rikaye** [ggreen86/XLXS-Workbook-Class#1]
Here’s the scenario.
I am using the SaveTableTWorkbook method.
My temp table (a cursor actually) has 2 fields – a char(135) and a memo.
The char field data is like an abstract. It contains the first 135 characters of the memo field, which contains the entire description.
Because getStringRecord is only comparing the first 120 characters of the string, AddStringValue is not recognizing the contents of the memo field as a unique value to store. 
The final output in the workbook is then essentially the contents of the char field.

**Comment by rikaye** [comment]
Just tested the R23 release and it fixes this bug. There also appears to be a bit of a performance boost. Thanks for the rapid response, Greg.

**Comment by rikaye** [comment]
I have some anecdotal evidence that there may be a different issue now. Under some circumstances it appears that one of the internal XML files is not present. Working on duplicating this.

**Comment by rikaye** [comment]
I took an example of an XLSX file that is missing something, copied to a ZIP and extracted all the folders and files. Here's the dir listing of this file:

> Directory of  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\*
>  5/18/2017  10:46a        <DIR>    .
>  5/18/2017  10:46a        <DIR>    ..
>  5/18/2017  10:45a        <DIR>    DOCPROPS
>  5/18/2017  10:45a        <DIR>    XL
>  5/18/2017  10:45a        <DIR>    _RELS
>  5/18/2017  10:46a              0  DIRLIST.TXT
>  5/17/2017  10:13a          1,053  [CONTENT_TYPES].XML
>                1,053 bytes in 2 files and 5 dirs    4,096 bytes allocated
> 
>  Directory of  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\DOCPROPS\*
>  5/18/2017  10:45a        <DIR>    .
>  5/18/2017  10:45a        <DIR>    ..
>  5/17/2017  10:13a            340  APP.XML
>  5/17/2017  10:13a            654  CORE.XML
>                  994 bytes in 2 files and 2 dirs    8,192 bytes allocated
> 
>     Total for:  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\DOCPROPS\*
>                  994 bytes in 2 files and 2 dirs    8,192 bytes allocated
> 
>  Directory of  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\XL\*
>  5/18/2017  10:45a        <DIR>    .
>  5/18/2017  10:45a        <DIR>    ..
>  5/17/2017  10:13a        <DIR>    WORKSHEETS
>  5/17/2017  10:13a        <DIR>    _RELS
>  5/17/2017  10:13a         21,730  SHAREDSTRINGS.XML
>  5/17/2017  10:13a            935  STYLES.XML
>  5/17/2017  10:13a            309  WORKBOOK.XML
>               22,974 bytes in 3 files and 4 dirs    32,768 bytes allocated
> 
>  Directory of  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\XL\WORKSHEETS\*
>  5/17/2017  10:13a        <DIR>    .
>  5/17/2017  10:13a        <DIR>    ..
>  5/17/2017  10:13a        763,956  SHEET1.XML
>              763,956 bytes in 1 file and 2 dirs    765,952 bytes allocated
> 
>     Total for:  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\XL\WORKSHEETS\*
>              763,956 bytes in 1 file and 2 dirs    765,952 bytes allocated
> 
>  Directory of  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\XL\_RELS\*
>  5/17/2017  10:13a        <DIR>    .
>  5/17/2017  10:13a        <DIR>    ..
>  5/17/2017  10:13a            564  WORKBOOK.XML.RELS
>                  564 bytes in 1 file and 2 dirs    4,096 bytes allocated
> 
>     Total for:  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\XL\_RELS\*
>                  564 bytes in 1 file and 2 dirs    4,096 bytes allocated
> 
>     Total for:  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\XL\*
>              787,494 bytes in 5 files and 8 dirs    802,816 bytes allocated
> 
>  Directory of  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\_RELS\*
>  5/18/2017  10:45a        <DIR>    .
>  5/18/2017  10:45a        <DIR>    ..
>  5/17/2017  10:13a            586  .RELS
>                  586 bytes in 1 file and 2 dirs    4,096 bytes allocated
> 
>     Total for:  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\_RELS\*
>                  586 bytes in 1 file and 2 dirs    4,096 bytes allocated
> 
>     Total for:  ...\EXPORT\BUYER_SALE_JOURNAL_20170517101330\*
>              790,127 bytes in 10 files and 17 dirs    819,200 bytes allocated
>      716,597,174,272 bytes free
>

**Comment by rikaye** [comment]
My standard implementation is to have an instance of the class on any form where I want to export to Excel. The UI will have various filtering options to retrieve the data to be exported. I am able to duplicate this new problem by running consecutive exports. The first export is fine. The second export is bad. When attempting to view the exported file using the Open XML SDK I get this dialog:

Open XML SDK 2.5 Productivity Tool for Microsoft Office
Cannot open the file: Specified part does not exist in the package.

The following VFP code snippet is basically how I've been doing this:

m.lcAlias=ALIAS()
m.savePath=[]
SHSPECIALFOLDER(0x0005,@savePath)
m.fname=PUTFILE(.msgsavechanges, ADDBS(m.savePath)+ALLTRIM(STRTRAN(.Caption,[ ],[_]))+[_]+ALLTRIM(TTOC(DATETIME(),1))+'.xlsx', 'XLSX')
.exp2XLSX.deleteallworkbooks()
SELECT (m.lcAlias)
m.loResult=.exp2XLSX.SaveTableToWorkbook(m.lcAlias, m.Fname, .t., .t.)

**Comment by rikaye** [comment]
I've now had some reports of shifted or missing data with the new checksum version. I'm testing this now and can again duplicate the problem. It is finding a match to a checksum for strings that are not the same.

**Comment by rikaye** [comment]
I can send you a sample VFP table, Greg.

**Comment by rikaye** [comment]
More clues. I can eliminate this latest issue by insuring that EXACT is ON. If EXACT is OFF, the SEEK() in GetStringID will return true for partial matches.

**Comment by rikaye** [comment]
If I put SET EXACT ON in the GetStringRecord method it solves this latest issue. I would guess that you need to do that in all the methods where you are RETURNing a SEEK() function value.

**Comment by rikaye** [comment]
The R23 alpha you sent me is looking good so far and has also added another bit of a performance boost. Still testing here but feeling positive so far.

**Comment by ggreen86** [comment]
Both of these issues - the string addition issue and the 'missing' file issue has now been corrected in Release 23.
