### ISSUE TITLE
Prevent sheet name from being too long

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLXS-Workbook-Class#12]
If you name a sheet within an Excel document with a string that's more than 31 characters, Excel reports that the file damaged and the "repair" it does is to truncate the sheet name to 31 characters. I suggest not allowing a sheet name to be more than 31 characters: either give an error or truncate the sheet name.

**Comment by DougHennig** [comment]
I'm using SaveGridToWorkbookEx but it applies to any method that accepts a sheet name.

**Comment by ggreen86** [comment]
thank you -- will look into limiting the name.


________________________________

**Comment by ggreen86** [comment]
I have added limit checks for the sheet name in the methods.  I also added checks for illegal characters in the sheet name as well.
