### ISSUE TITLE
Variable 'tcstring' not found in readsharedstringsxml

### ISSUE THREAD

**Issue by rikaye** [ggreen86/XLXS-Workbook-Class#2]
Greg,

I'm having a play with reading an Excel doc and running into this error in readsharedstringsxml when the code shown below executes:

```
INSERT INTO xl_strings (id, workbook, checksum, stringxml, stringval, presvspace, formatted) ;
			VALUES (lnNode-1, tnWB, this.GetCheckSum(tcString), lcText, this.GetStringXML(lcText), llPrsvSp, llFormatted)

```
My wild guess is that the tcString ref should be lcString?

**Comment by rikaye** [comment]
And changing that ref appears to make it happy.

**Comment by ggreen86** [comment]
Yes I found that bug also and was also fixing some other issues as well.  I need to upload the next release...


________________________________

**Comment by ggreen86** [comment]
I have fixed the issue -- probably caused by a search-n-replace (not actually sure but this is the most probable cause).  The variable tcString should be lcString.
