### ISSUE TITLE
When exporting from grid, ColumnOrder of columns in grid is not honored...

### ISSUE THREAD

**Issue by mattslay** [ggreen86/XLXS-Workbook-Class#4]
Notice the ColumnOrder of each column in this grid (see screenshot). They are not in the same order as the actual columns collection in the grid, because at design time of the grid, I have re-arranged the column order. For instance, Column5 may well have ColumnOrder of 2, and so on.

Yet when exported using the SaveGridToWorkbookEx() method, the columns are ordered in the sequential Column1, Column2, Column3, etc order, but that is not the visual order of the grid, which is what the user will expect when they export to a spreadsheet.

UI Grid:
![image](https://user-images.githubusercontent.com/309016/30248437-813507a8-95ed-11e7-959d-40d404092034.png)

Excel spreadsheet:
![image](https://user-images.githubusercontent.com/309016/30248477-1657f4bc-95ee-11e7-9dbf-6e3813af888f.png)

**Comment by ggreen86** [comment]
Actually the output order is not a bug but how it was coded; I just loop through the columns property to output.  This should actually be a feature request.

**Comment by mattslay** [comment]
This has been fixed. Thanks Greg.
