### ISSUE TITLE
Please guide how to simply import xlsx into cursor

### ISSUE THREAD

**Issue by dearirfan** [ggreen86/XLXS-Workbook-Class#5]
Dear Sir,
Please guide how to simply import xlsx into cursor using xlsx-workbook class.
I've tried my level best by reading given documentation but failed.

Thanking you,
Best regards,
Irfan

**Comment by ggreen86** [comment]
Look at ReadXlsxFile.prg which is below:


PUBLIC goExcel   && to keep it from being destroyed and closing the cursors
LOCAL lcFile, lnWb, loSheets, lnSh, lnRow, lnCol
lcFile = GETFILE("xlsx", "Workbook", "Load", 0, "Select Workbook to load into Class")
IF !EMPTY(lcFile)
 goExcel = NEWOBJECT("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx")
 lnWb = goExcel.OpenXlsxWorkbook(lcFile)
 loSheets = goExcel.GetWorkbookSheets(lnWb)
 FOR lnSh=1 TO loSheets.Count
  ? loSheets.List[lnSh, 1]      && Displays sheet index (which may not be the same as lnSh)
  ? loSheets.List[lnSh, 2]      && Displays sheet name
  FOR lnRow=1 TO goExcel.GetLastRowNumber(lnWb, loSheets.List[lnSh, 1])
   FOR lnCol=1 TO goExcel.GetMaxColumnNumber(lnWb, loSheets.List[lnSh, 1])
    IF goExcel.IsCellFormula(lnWb, loSheets.List[lnSh, 1], lnRow, lnCol)
     ? goExcel.GetCellFormula(lnWb, loSheets.List[lnSh, 1], lnRow, lnCol)
    ELSE
     ? goExcel.GetCellValue(lnWb, loSheets.List[lnSh, 1], lnRow, lnCol)
    ENDIF
   ENDFOR
  ENDFOR
 ENDFOR
ENDIF



________________________________

**Comment by dearirfan** [comment]
Dear Sir,
Thanks very much for your kind reply.

Sir I’m average user (learner) of VFP . This example is included in class related documents. Kindly guide me where is “Cursor” contained of imported excel data in this example.

Thanking you,
Hoping for a kind guidance.

Best regards,
Irfan





Sent from Mail for Windows 10

**Comment by ggreen86** [comment]
Irfan--

The cursors are not "meant" to be accessed directly; although you can.  The cursor names all begin with "xl_".  There are methods for getting the cell values, formatting, and formulas.  See all the methods that start with "Get" in the name.

Greg

________________________________

**Comment by dearirfan** [comment]
Thank you Sir for your kind reply. I’ll try that.

Best regards,
Irfan


Sent from Mail for Windows 10
