### ISSUE TITLE
SaveTableToWorkbookEx

### ISSUE THREAD

**Issue by SeregaKR** [ggreen86/XLXS-Workbook-Class#6]
Good evening.
I try to save cursor to xlsx file. I need to set headers different from field names in cursor.
I try to do it like in example provided with the release:

I create an array with field names and headers.
```
lcTable = GETFILE("dbf", "table", "Export", 0, "Select Table to Export")
IF !EMPTY(lcTable)
	lcAlias = CHRTRAN(JUSTSTEM(lcTable), " ", "")
	IF !USED(lcAlias)
		USE (lcTable) IN 0 EXCLUSIVE ALIAS &lcAlias
	ENDIF
	SELECT &lcAlias
	DIMENSION fld_list(4,2)
	fld_list(1,1) = lcAlias+".fam"
	fld_list(1,2) = "Surname"
	fld_list(2,1) = lcAlias+".nam"
	fld_list(2,2) = "Name"
	fld_list(3,1) = lcAlias+".snam"
	fld_list(3,2) = "Middle name"
	fld_list(4,1) = lcAlias+".drpc"
	fld_list(4,2) = "Birthday"

	loExcel = NEWOBJECT("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx")
	loExcel.Savetabletoworkbookex(lcAlias, lcAlias + "_test2.xlsx", fld_list, .T., lcAlias)

	USE IN SELECT(lcAlias)
ENDIF
```

But I get the error tafields.prg does not exist. What's wrong with the code? It seems (checked in debugger) that fld_list[1,1] value is passed in class but not the whole array. Also tried even this variants:
```
loExcel.Savetabletoworkbookex(lcAlias, lcAlias + "_test2.xlsx", &fld_list, .T., lcAlias)
loExcel.Savetabletoworkbookex(lcAlias, lcAlias + "_test2.xlsx", "fld_list", .T., lcAlias)
```

...but still no luck(

**Comment by ggreen86** [comment]
Try passing the array by reference with the @ sign as follows:


loExcel.Savetabletoworkbookex(lcAlias, lcAlias + "_test2.xlsx", @fld_list, .T., lcAlias)

Otherwise only the first value is passed and not as an array.

________________________________

**Comment by SeregaKR** [comment]
Thank you. I wiil try it tomorrow. 
It's strange actually. I have similar piece of code but it works. Maybe the reason is that in my case I launch it from menu procedure.

**Comment by SeregaKR** [comment]
It works. Thank you.
