### ISSUE TITLE
SaveGridToWorkbookEx returns true even if error occurs

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLXS-Workbook-Class#7]
SaveGridToWorkbookEx has this code near the end:
```foxpro
IF llError
	llSuccess = False
ENDIF

*-*	Create the XLSX file
this.CreateExcelFile(lcTempPath, JUSTPATH(tcFileName), JUSTSTEM(tcFileName))
this.RemoveWorkingDirectories(lcTempPath)
llSuccess = True
```
If an error occurred earlier, llSuccess is set to false. However, it's then set to true after calling CreateExcelFile and RemoveWorkingDirectories. I think the code should look like this instead:
```foxpro
IF llError
	llSuccess = False
else
*-*	Create the XLSX file
	this.CreateExcelFile(lcTempPath, JUSTPATH(tcFileName), JUSTSTEM(tcFileName))
	llSuccess = True
ENDIF
this.RemoveWorkingDirectories(lcTempPath)
```
Doug

**Comment by ggreen86** [comment]
I have incorporated the changes that you list above in the current release of the class.  Thank you for your help.
