### ISSUE TITLE
Init doesn't save/restore work area

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLXS-Workbook-Class#8]
Init should use code like this:
```foxpro
LPARAMETERS tnCodePage
LOCAL lnSelect, loException
lnSelect = select()
... rest of code
this.OnInit()
select (lnSelect)
```
so the current work area is saved and restored.

Doug

**Comment by ggreen86** [comment]
Doug--


I will add this to the next release which will be soon (as well as the other earlier email suggestion).  I have also made some changes for reading in spreadsheets that the cells have inline text.

Greg

________________________________

**Comment by ggreen86** [comment]
Added your suggestion to the current release of the class.  Thank you.
