### ISSUE TITLE
Please help with query export

### ISSUE THREAD

**Issue by stevendbrady** [ggreen86/XLXS-Workbook-Class#9]
I've been using VFP for many years, but I'm still a novice. Right now I use it to run reports against a database, then export to an Excel file. I'd like to save to XLSX using your class, but I really have no idea where to start.

Essentially, this is the basics of my programs, but I have no idea how to change it to XLSX instead. Can you help? I'm sorry for such a rudimentary question, especially since you've included so many examples, but I'm just completely lost. Thanks.

OPEN DATABASE dbname
USE queryname
EXPORT TO filename TYPE XL5

**Comment by ggreen86** [comment]
Have you looked at the Demo() method?  This shows an example of creating a spreadsheet and then saving data and formatting the cells.  There are two methods for saving a table or a grid directly -- see SaveGridToWorkbookEx() and SaveTableToWorkbookEx() methods.  There is a PRG in the ZIP archive that shows using these methods.


________________________________
